### ISSUE TITLE
Integrate recognition as a built-in device 

### ISSUE THREAD

**Issue by antoniomcr96** [0xFireWolf/RealtekCardReader#13]
First of all, thanks for all your work.
The idea that I want to propose consists of merging this kext with _RealtekCardReaderFriend_ in order to always show the card reader as a built in device.
Maybe we can use a boot-arg or (better) inject a deviceproperty to control this feature.
What do you think?
Thanks in advance

**Comment by 0xFireWolf** [comment]
No, I deliberately choose not to combine them into a single kext, otherwise `RealtekCardReader` always depends on `Lilu` regardless of whether users want to turn on the features provided by `RealtekCardReaderFriend`.

**Comment by antoniomcr96** [comment]
Thanks for the explaination. Anyway, in a real-life scenario, I think that everyone who needs this kext uses Lilu. Have a nice day :)
