### ISSUE TITLE
Not recognizable as a built-in card reader device

### ISSUE THREAD

**Issue by git897** [0xFireWolf/RealtekCardReader#24]
First thank you for your help that i can use the sd card.  But the computer not recognizable as a built-in card reader device.It just display in storage page.i also use the cardreader friend kext.but it doesn't work
![截屏2021-11-30 上午12 54 48](https://user-images.githubusercontent.com/59389240/143910624-fdb3b809-e75c-46d2-af50-78ba1dd3595d.png)
![Screen Shot 2021-11-30 at 12 43 07 AM](https://user-images.githubusercontent.com/59389240/143910658-27e0b804-05ee-44bd-bc62-8f61b4ccaf15.png)
![Screen Shot 2021-11-30 at 12 44 31 AM](https://user-images.githubusercontent.com/59389240/143910663-98ef2131-1e93-4d27-8a24-381e53f43b7e.png)

**Comment by 0xFireWolf** [comment]
Please identify your SD card reader.
i.e. Device name, vendor ID, device ID, etc.

**Comment by git897** [comment]
![屏幕截图 2021-12-01 040756](https://user-images.githubusercontent.com/59389240/144170731-1504cdd0-c25a-46c1-8972-86098198847a.png)

**Comment by 0xFireWolf** [comment]
Please refer to the [README](https://github.com/0xFireWolf/RealtekCardReader#features) and make sure that you have both RealtekCardReader and RealtekCardReaderFriend installed on your computer.
