### ISSUE TITLE
RTS5250 PCI-E Support

### ISSUE THREAD

**Issue by gemini444** [0xFireWolf/RealtekCardReader#29]
Hello all,
First of all, thank you very much to the developers. 
My laptop MSI-Prestige-15 and Model A10SC. It has RTS5250 PCI-E micro sd card reader. I tried Realtek Card Reader Driver and friend kexts but no luck.
Is there a way to get this card working, or do you plan to support it in the future? I attached my ioreg and screenshots.
Thanks a lot.
<img width="904" alt="Screen Shot 2021-12-11 at 21 02 06" src="https://user-images.githubusercontent.com/40460434/145686927-7b30aea6-d77f-46c1-a8b3-30ac1a1a9bf8.png">
<img width="1839" alt="Screen Shot 2021-12-11 at 21 02 35" src="https://user-images.githubusercontent.com/40460434/145686929-4996f0e0-f17e-44cc-9ae0-e483814117c0.png">
[prestige MacBook Pro.ioreg.zip](https://github.com/0xFireWolf/RealtekCardReader/files/7697513/prestige.MacBook.Pro.ioreg.zip)

**Comment by 0xFireWolf** [comment]
See https://github.com/0xFireWolf/RealtekCardReader/issues/23.
