### ISSUE TITLE
Artifacts expired

### ISSUE THREAD

**Issue by Genxster1998** [0xFireWolf/RealtekCardReader#32]
I cannot able to setup xcode on my pityful system and latest patches are there for Mojave support on 0.9.7 but your ci artifacts are expired .Is there another source for   latest release ?
Thanks , trying to test on High Sierra ...

**Comment by 0xFireWolf** [comment]
[RealtekCardReader_0.9.7_f857f82_DEBUG.zip](https://github.com/0xFireWolf/RealtekCardReader/files/8697637/RealtekCardReader_0.9.7_f857f82_DEBUG.zip)
[RealtekCardReader_0.9.7_f857f82_RELEASE.zip](https://github.com/0xFireWolf/RealtekCardReader/files/8697638/RealtekCardReader_0.9.7_f857f82_RELEASE.zip)
