### ISSUE TITLE
RTS5227 PCI Express Card Reader

### ISSUE THREAD

**Issue by chris1111** [0xFireWolf/RealtekCardReader#33]
Not working here on my HP Probook 650 G1
It work with Sinetek-rtsx.kext but I would have liked to use your kext
This is the Infos from Hackintool

`04:00.0 10EC 5227 103C 2101 L0s+L1 Realtek Semiconductor Co., Ltd RTS5227 PCI Express Card Reader                    Unassigned class     ???                  /pci10ec,5227@0 pci10ec,5227    PciRoot(0x0)/Pci(0x1C,0x7)/Pci(0x0,0x0) `

**Comment by 0xFireWolf** [comment]
Please attach the **complete** kernel log as per [FAQ](https://github.com/0xFireWolf/RealtekCardReader/blob/main/Docs/FAQ.md#how-do-i-dump-the-log-produced-by-the-driver). Issues without kernel logs or with incomplete kernel logs will be ignored and closed.

**Comment by chris1111** [comment]
Ok sorry for the Faq and the Log but now with the boot args  `msgbuf=10485760`
the system not boot any more, kenel panic ?

**Comment by chris1111** [comment]
Sorry My fault issue booting is resolved, here Log 

[rtsx.log.zip](https://github.com/0xFireWolf/RealtekCardReader/files/8703751/rtsx.log.zip)

**Comment by chris1111** [comment]
strangely since I managed to boot with the debug the SD card mounts well and moreover I can eject and put back a different one which I cannot do with the kext sinetek.

Now it seems to work fine only it doesn't show up in About This Mac, I have to enter DeviceProperties

![Screen Shot 2022-05-16 at 6 28 41 PM](https://user-images.githubusercontent.com/6248794/168694533-5e24d50b-b5e0-4941-ab60-39e066d7983f.png)

the release kext is loaded correctly
![Screen Shot 2022-05-16 at 6 42 21 PM](https://user-images.githubusercontent.com/6248794/168694545-2b215602-d9d2-4fd6-a300-96f85aad4963.png)

**Comment by 0xFireWolf** [comment]
Your attached kernel log has no error messages and all recorded I/O transactions have succeeded.

> Now it seems to work fine only it doesn't show up in About This Mac, I have to enter DeviceProperties

Device Properties are not needed.

As mentioned in the [Features](https://github.com/0xFireWolf/RealtekCardReader#features) section in the README file, you need to install the companion Lilu plugin [RealtekCardReaderFriend](https://github.com/0xFireWolf/RealtekCardReaderFriend/) to make your card reader recognized as a built-in one.

**Comment by chris1111** [comment]
ok Now I have an update monterey and I will test later tonight

**Comment by chris1111** [comment]
Yes it work Thank you very mutch
![Screen Shot 2022-05-16 at 6 28 41 PM](https://user-images.githubusercontent.com/6248794/168704021-89e4e17a-3e0a-4316-b9ba-bd7926676ba2.png)

**Comment by Agustine808** [comment]
![Screen Shot 2023-07-31 at 3 33 03 PM](https://github.com/0xFireWolf/RealtekCardReader/assets/64139174/07e21318-b449-435f-a3ee-e925b0f75dfc)
how to remove type which is mentioned here as "unassigned class"? @0xFireWolf

**Comment by Agustine808** [comment]
> strangely since I managed to boot with the debug the SD card mounts well and moreover I can eject and put back a different one which I cannot do with the kext sinetek.
> 
> Now it seems to work fine only it doesn't show up in About This Mac, I have to enter DeviceProperties
> 
> ![Screen Shot 2022-05-16 at 6 28 41 PM](https://user-images.githubusercontent.com/6248794/168694533-5e24d50b-b5e0-4941-ab60-39e066d7983f.png)
> 
> the release kext is loaded correctly ![Screen Shot 2022-05-16 at 6 42 21 PM](https://user-images.githubusercontent.com/6248794/168694545-2b215602-d9d2-4fd6-a300-96f85aad4963.png)

how did you managed to hands on memory card type "secure digital memory card? when mine is unassigned class in type!
