### ISSUE TITLE
Not working on Sierra

### ISSUE THREAD

**Issue by TieLie** [0xFireWolf/RealtekCardReader#34]
Hi. I tried it on Sierra 10.12.6(Max version for Intel HD Graphics 3000 where aren't any glitches) and it's not working. My Card Reader is RTS5209, My Laptop is Lenovo Thinkpad L420. When I was using Catalina 10.15.7 it was working perfectly, but it's not working at all on Sierra

**Comment by 0xFireWolf** [comment]
As clearly indicated in [README](https://github.com/0xFireWolf/RealtekCardReader#supported-systems), macOS Sierra is not supported. You may need to adjust the deployment target in Xcode, change the value of `OSBundleLibraries` in `Info.plist` and recompile the driver to make it work on older systems.
