### ISSUE TITLE
Generic RealtekCardReader

### ISSUE THREAD

**Issue by pierpaolodimarzo** [0xFireWolf/RealtekCardReader#36]
Hi, 
I'm having a big problems with my USB3.0 card reader not being recognized.
My Laptop is Thinkpad T480
The reader is defined as: 0x0bda - 0x0316
I tried to edit the kext but it still doesn't get recognized
I also tried kext Generic, but to no avail.
how can i fix?

Thanks

**Comment by 0xFireWolf** [comment]
Your card reader is not supported and will not be supported by this driver. In fact, it implements the UAS protocol, so in theory it should be natively supported by Apple’s USB driver if your USB ports are mapped properly. Please seek help on forums.
