### ISSUE TITLE
Kext wont load for Mojave

### ISSUE THREAD

**Issue by mslifcak** [0xFireWolf/RealtekCardReader#40]
RealtekCardReader.kext does not load on 10.14.6 Mojave
Observed using Clover 5148 or OpenCore 0.8.3. 
  There is no such problem for 10.15, 11, 12 or 13.

Hardware:  Dell Latitude 7480, Board 00F6D3
Realtek 525A Vendor ID: 0x10ec   Device ID: 0x525a
Subsystem Vendor ID: 0x1028  Subsystem ID: 0x07a0  Revision ID: 0x0001

Clover misc/preboot.log shows no error for the kext

OpenCore efi log for Mojave has one line:
  OC: Prelinked Injection (RealtekCardReader.kext (Realtek SDCard Reader (0xFireWolf)) - Invalid Parameter

DebugEnhancer and msgbuf boot arg tried for both Clover and OpenCore.  No RTSX lines in kernel log

**Comment by gujiangjiang** [comment]
Dont foget RealtekCardReaderFriend.kext

**Comment by mslifcak** [comment]
Problem solved with this combination:
 RealtekCardReader.kext 0.9.7
 RealtekCardReaderFriend.kext 1.0.4
 
 Many thanks to all who helped build the working releases.
