### ISSUE TITLE
Support for Ventura

### ISSUE THREAD

**Issue by m0d16l14n1** [0xFireWolf/RealtekCardReader#41]
Hello! Can you please update a kext to support loding on Ventura, because it was released and out of beta? 

I know, it's possible to load it with proper boot-arg, but still :)

**Comment by sash11** [comment]
I am able to use kexts on Ventura fine, both update and clean installation on Dell XPS15-7590

**Comment by 0xFireWolf** [comment]
Both kexts (reader and friend) are working properly on my Ventura installation, but please checkout the latest releases (0.9.7 and 1.0.4).

**Comment by m0d16l14n1** [comment]
> Both kexts (reader and friend) are working properly on my Ventura installation, but please checkout the latest releases (0.9.7 and 1.0.4).

Thanks!
