### ISSUE TITLE
0x0bda 0x129 not working

### ISSUE THREAD

**Issue by albyvar25** [0xFireWolf/RealtekCardReader#5]
I tried the kexts RealtekCardReader and RealtekCardReaderFriend with Lilu but it doesn't work (it isn't recognized)

In system info it shows as usb 2.0-crw 

Notebook model: Chuwi CoreBook Pro

**Comment by albyvar25** [comment]
Sorry, nvm. I saw the new 0.9.6 release and the work in progress to get this model to work. Tried it and I have the same issues described in the post. Thanks for your work!

**Comment by gnpaone** [comment]
> Sorry, nvm. I saw the new 0.9.6 release and the work in progress to get this model to work. Tried it and I have the same issues described in the post. Thanks for your work!

Did it work for you?
