### ISSUE TITLE
[feedback] XPS 9570 works well.

### ISSUE THREAD

**Issue by M69W** [0xFireWolf/RealtekCardReader#6]
macOS version：10.15.7 (19H1323)
XPS 9570：RTS525A
EFI: [xxxzc/xps15-9570-macos](https://github.com/xxxzc/xps15-9570-macos)

![image](https://user-images.githubusercontent.com/15809201/126904053-2d78338f-6bef-4c40-a36e-3ddc426f3dae.png)

**Comment by 0xFireWolf** [comment]
Thank you for testing the driver.

Do you have UHS-I SDHC or SDXC cards to test the I/O performance under macOS?

**Comment by M69W** [comment]
Only SDSC Card now, maybe will update when I have these cards.

**Comment by M69W** [comment]
Only SDSC Card now, maybe will update when I have these cards.

**Comment by 0xFireWolf** [comment]
Sure. Thank you.
