### ISSUE TITLE
RTS5129 (0x129 0xbda) issue

### ISSUE THREAD

**Issue by gnpaone** [0xFireWolf/RealtekCardReader#8]
Hi @0xFireWolf you are doing a great job in developing the kext for card reader. As you mentioned in 0.9.5 changelog, I did add both the kexts but nothing changed for RTS5129, it's same as before. I am using opencore and I have attached some pics too. You also mentioned that you don't have this card reader with you right? I can help you with whatever tests you need to do with the card reader as I have it but please make it work.
![Screenshot 2021-08-03 at 2 21 20 PM](https://user-images.githubusercontent.com/78990165/127988297-d06deabc-7ed1-4289-9900-b2cca65c2338.png)
![Screenshot 2021-08-03 at 2 17 25 PM](https://user-images.githubusercontent.com/78990165/127988339-46565452-be33-4dfe-831e-ae2f60a9ab6a.png)
![Screenshot 2021-08-03 at 2 17 07 PM](https://user-images.githubusercontent.com/78990165/127988344-7c10cd64-8f8c-4e71-83d2-a82151d4dc35.png)
![Screenshot 2021-08-03 at 2 17 01 PM](https://user-images.githubusercontent.com/78990165/127988346-9af73977-d7b9-434d-a393-3b1212cac2cd.png)

**Comment by m0d16l14n1** [comment]
You can find all info here, there is the topic with testers and test builds. Work in progress, so it's still unknown when it's will work "fully" 

https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/

**Comment by gnpaone** [comment]
Update: I removed the both realtekcardreader and realtekcardreaderfriend kexts and replaced it with genericcardreaderfriend kext by @0xFireWolf and it does show up in card reader list but doesn't detect any scared when inserted (I think it's mentioned generic kext creates a fake sdcard reader probably 🤔) but it's still the same look in "USB" of "system report"

![Screenshot 2021-08-03 at 3 48 02 PM](https://user-images.githubusercontent.com/78990165/128000133-014a9fe3-013e-45f9-87e5-86fafb8dab97.png)

**Comment by gnpaone** [comment]
> @gnpaone You can find all info here, there is the topic with testers and test builds. Work in progress, so it's still unknown when it's will work "fully"
> 
> https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/

Thanks, I will follow the forum

**Comment by gnpaone** [comment]
> > @gnpaone You can find all info here, there is the topic with testers and test builds. Work in progress, so it's still unknown when it's will work "fully"
> > https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/
> 
> Thanks, I will follow the forum

https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764183

**Comment by gnpaone** [comment]
> > > @gnpaone You can find all info here, there is the topic with testers and test builds. Work in progress, so it's still unknown when it's will work "fully"
> > > https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/
> > 
> > 
> > Thanks, I will follow the forum
> 
> https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764183
> 
> https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764198

https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764430  @0xFireWolf

**Comment by gnpaone** [comment]
> > > > @gnpaone You can find all info here, there is the topic with testers and test builds. Work in progress, so it's still unknown when it's will work "fully"
> > > > https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/page/4/
> > > 
> > > 
> > > Thanks, I will follow the forum
> > 
> > 
> > https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764183
> > https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764198
> 
> https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764430
> 
> https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764472 @0xFireWolf

https://www.insanelymac.com/forum/topic/348130-realtek-pcie-card-reader-driver-for-macos/?do=findComment&comment=2764505 @0xFireWolf

**Comment by m0d16l14n1** [comment]
@gnpaone please, stop spamming your own comments. Once dev will have time, he will look, no need to quote and ping every time you post something ^_^

**Comment by gnpaone** [comment]
Fine

**Comment by 0xFireWolf** [comment]
The latest 0.9.6 release has resolved the issue that cards cannot be initialized properly on USB-based card readers.
Issue closed. If the original poster has found other issues with the latest release, please create a new issue with complete kernel logs.
