### ISSUE TITLE
Disk Not Ejected Properly after wake from sleep

### ISSUE THREAD

**Issue by VinylNerd** [0xFireWolf/RealtekCardReader#9]
Hello

i am using latest 0.9.6 with the helper kext aswell

T440P RTS5227 Big Sur 11.5.2

After wake from sleep get this notification saying the disk was not ejected properly, if i plug the same SD into an SD adapter or USB the notification does not exist.

Thanks

**Comment by 0xFireWolf** [comment]
Such behavior is expected for now.
